### ISSUE TITLE
I keep getting this error in my service. I'm not sure what I'm doing wrong

### ISSUE THREAD

**Issue by Oshianor** [whefter/nestjs-joi#16]
Here is a validation i have written
```
export class validatePhoneNumber {
  @JoiSchema(Joi.string()
    .label("Phone Number")
    .regex(/^[1-9][0-9]{9}$/)
    .required()
    .messages({
      "string.pattern.base": `Phone Number can't not have a leading zero (0)`,
    }))
  phoneNumber!: string;

  @JoiSchema(Joi.string().max(6).required())
  countryCode!: string;
}


ERROR [RpcExceptionsHandler] Invalid JoiPipeOptions:
- Unknown configuration keys: pattern, data, context
Error: Invalid JoiPipeOptions:
- Unknown configuration keys: pattern, data, context
    at JoiPipe.parseOptions (C:\Users\abund\projects\saveup\user-service\node_modules\nestjs-joi\internal\joi.pipe.js:115:19)
    at new JoiPipe (C:\Users\abund\projects\saveup\user-service\node_modules\nestjs-joi\internal\joi.pipe.js:62:30)
    at Injector.instantiateClass (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\core\injector\injector.js:330:19)
    at callback (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\core\injector\injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Injector.loadInstance (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\core\injector\injector.js:52:9)
    at async Promise.all (index 0)
    at Injector.loadEnhancersPerContext (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\core\injector\injector.js:355:9)
    at Injector.loadPerContext (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\core\injector\injector.js:345:9)
    at requestScopedHandler (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\microservices\listeners-controller.js:93:41)
    at ServerRMQ.handleMessage (C:\Users\abund\projects\saveup\user-service\node_modules\@nestjs\microservices\server\server-rmq.js:104:54)
```

**Comment by whefter** [comment]
It is likely this has nothing to do with the schema definition. Where are you instanting the pipe which uses that schema/where are you including `JoiPipeModule`? Please include the relevant lines.

**Comment by Oshianor** [comment]
I'm instantiating the `JoiPipeModule` within my app.module.ts file. Whenever I send a request to that service I immediately get the above error
```

import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import { UserModule } from './user/user.module';
import { JoiPipeModule } from 'nestjs-joi';

@Module({
  imports: [
    JoiPipeModule,
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    MongooseModule.forRoot(process.env.DATABASE_URL),
    UserModule,
  ]
})
export class AppModule {}

```

**Comment by whefter** [comment]
This module has not been tested or validated with a microservice-based NestJS service. I'm assuming the pipe is received weird and unexpected input. I'd have to look into making it compatible, if it is possible.

**Comment by whefter** [comment]
Microservice support added in https://github.com/whefter/nestjs-joi/commit/d9b6a6e5f7af9bf07eecb959f61951c7793ac3db
