### ISSUE TITLE
 Using JoiSchema for custom Error in Joi throws  Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sreeteja06** [whefter/nestjs-joi#4]
Usage
```
@JoiSchema(
    Joi.string()
      .required()
      .trim()
      .regex(passwordPattern)
      .error(
        new Error(
          `password must contain 1 number, 1 upper, 1 lower, 1 special and should be 8 chars long`,
        ),
      ),
  )
  password: string;
```

Error
```
TypeError: Cannot read property 'map' of undefined
    at Function.validate (P:\Projects\9and9\srisailam\srisailam-backend\node_modules\nestjs-joi\internal\joi.pipe.js:78:43)
    at JoiPipe.transform (P:\Projects\9and9\srisailam\srisailam-backend\node_modules\nestjs-joi\internal\joi.pipe.js:73:26)
```

**Comment by whefter** [comment]
Thanks for the submission, fixed in v1.3.1. Custom errors are now passed through.
